### ISSUE TITLE
Spaces and label axes

### ISSUE THREAD

**Issue by egleich** [JOfTheAncientGermanSpear/circro#1]
Reminder of the two things we talked about:

1) Blank space in the circle whenever there's a blank row in the file
2) Changing the orientation of the axis for each label so that they aren't horizontally, but aligned with the angle at which each ROI is placed

**Comment by jcmosher** [comment]
I edited writeLabels to orient the labels radially, and align them more tightly on a circle. For your consideration, my mods (by adding theta_display and 'Rotation'):

function writeLabels(labels, radius,startRadian)
    regions=[labels(:,1);flipud(labels(:,2))]; % flip right hemisphere regions
    numberLabels=size(regions,1);
    for i=1:numberLabels  
        theta=  ( (startRadian + ( (i-1) _(2_pi/numberLabels) ))...
            + (startRadian + ( (i _(2_pi/numberLabels) )) ))/2 ; 
        theta_display = theta;
        Alignment = 'left';
        if cos(theta_display) < 0,
            theta_display = theta_display + pi;
            Alignment = 'right';
        end
        theta_display = theta_display/pi*180;
        theta_display = rem(theta_display,360);

```
    x = radius * cos(theta);
    y = radius * sin(theta);        
    if ischar(regions{i})
        name=regions{i};
    else
        name=num2str(regions{i});
    end        
    text(x*(1.1), y*(1.1), name, 'HorizontalAlignment',Alignment,'FontSize',10,'Rotation',theta_display)               
end    
```

% end write labels

**Comment by JOfTheAncientGermanSpear** [comment]
Great work JcMosher, & thank you for the contribution!

So that you may have credit for implementing the feature in the commit history, may you perform the following steps:
1) Fork the repository
2) Implement the change & commit it
3) Create a pull request once complete

Than I will make sure the code works as expected & pull it in to this repository.

Let me know if you need any assistance.

**Comment by jcmosher** [comment]
Thanks for posting, JOTAGS. I'm not very GITHUB savvy and don't really have time to learn at the moment, but I'm glad to have been of some help.

**Comment by JOfTheAncientGermanSpear** [comment]
I understand.
So that credit is given the contribution is mentioned in the:
1. [readme](https://github.com/bonilhamusclab/circro#contributions)
2. In the code as a [comment](https://github.com/bonilhamusclab/circro/blob/master/%2Bdrawing/%2Bcircro/writeLabels.m)
3. [Commit message](https://github.com/bonilhamusclab/circro/commit/8bf038a397b004f319f1c0054dac3d842bbffb60)
